### ISSUE TITLE
Cannot extract bursts

### ISSUE THREAD

**Issue by cucim** [jboone/tpms#3]
Hi,
i cannot extract bursts.
executing ./extract_bursts.py capture.cfile
gives me following error:
Traceback (most recent call last):
  File "./extract_bursts.py", line 83, in <module>
    tb = top_block(sys.argv[1])
  File "./extract_bursts.py", line 47, in **init**
    target_signal, carrier_freq, sampling_rate, start_date, start_time, capture_device = source_filename.split('_')
ValueError: need more than 1 value to unpack

**Comment by alynx7** [comment]
Looking at the code you can see that the filename should respect a given format:
target_signal, carrier_freq, sampling_rate, start_date, start_time, capture_device separated by '_'
The extension is not important.

Hope this could help you.
